import requests

# List of URLs to check
urls = [
	"https://bettersquash.com/3-reasons-why-you-should-be-able-to-serve-backhand/",
	"https://bettersquash.com/3-secret-squash-tips-i-never-thought-i-would-share-with-my-online-pupils/",
	"https://bettersquash.com/3-suggestions-when-visiting-a-pro-squash-tournament/",
	"https://bettersquash.com/3-things-squash-players-can-learn-from-tennis-players/",
	"https://bettersquash.com/5-cs-to-improve-your-squash/",
	"https://bettersquash.com/5-squash-scoring-challenges-for-club-players-to-help-improve-their-tactics/",
	"https://bettersquash.com/5-things-to-try-on-your-bad-days/",
	"https://bettersquash.com/a-brief-introduction-to-shot-selection-in-squash/",
	"https://bettersquash.com/a-drill-and-a-ghost/",
	"https://bettersquash.com/ability-squash-rackets-and-video-cameras/",
	"https://bettersquash.com/an-open-letter-to-aspiring-squash-juniors/",
	"https://bettersquash.com/are-all-brands-of-squash-ball-the-same/",
	"https://bettersquash.com/are-all-squash-courts-the-same-size/",
	"https://bettersquash.com/are-court-sprints-good-for-your-squash/",
	"https://bettersquash.com/are-you-allowed-to-jump-when-you-hit-the-ball-in-squash/",
	"https://bettersquash.com/are-you-allowed-to-swing-more-than-once-on-a-squash-shot/",
	"https://bettersquash.com/are-you-fit-enough-to-play-squash/",
	"https://bettersquash.com/beautiful-squash-courts-part-1/",
	"https://bettersquash.com/better-to-be-accurate-than-powerful-my-80-80-philosophy/",
	"https://bettersquash.com/beware-defensive-boasts/",
	"https://bettersquash.com/buying-second-hand-squash-rackets/",
	"https://bettersquash.com/can-i-serve-overarm-in-squash/",
	"https://bettersquash.com/can-i-use-a-red-dot-ball-in-squash-solo-drills/",
	"https://bettersquash.com/can-you-become-a-great-player-without-a-coach/",
	"https://bettersquash.com/can-you-get-fit-just-playing-squash/",
	"https://bettersquash.com/can-you-have-squash-coaching-from-more-than-one-coach-at-a-time/",
	"https://bettersquash.com/can-you-hit-the-ball-with-two-hands-in-squash/",
	"https://bettersquash.com/can-you-make-contact-with-the-ball-outside-of-the-squash-court/",
	"https://bettersquash.com/can-you-play-doubles-on-a-singles-squash-court/",
	"https://bettersquash.com/can-you-play-squash-in-the-summer/",
	"https://bettersquash.com/can-you-practice-too-much/",
	"https://bettersquash.com/can-you-receive-coaching-during-a-squash-match/",
	"https://bettersquash.com/can-you-share-a-squash-coaching-lesson/",
	"https://bettersquash.com/can-you-swap-playing-hands-in-squash/",
	"https://bettersquash.com/can-you-talk-during-squash-rallies/",
	"https://bettersquash.com/can-you-use-two-rackets-at-the-same-time-in-squash/",
	"https://bettersquash.com/can-you-wear-gloves-when-you-play-squash/",
	"https://bettersquash.com/children-are-not-needed-for-squash-to-be-successful/",
	"https://bettersquash.com/consistent-squash-training/",
	"https://bettersquash.com/crosscourts-condition-drill/",
	"https://bettersquash.com/do-i-have-to-keep-my-racket-up-when-playing-squash/",
	"https://bettersquash.com/do-not-watch-the-ball-all-the-time-in-squash/",
	"https://bettersquash.com/do-pro-squash-players-volley-more-than-club-players/",
	"https://bettersquash.com/do-words-get-in-the-way-of-communication/",
	"https://bettersquash.com/do-you-have-to-play-squash-in-shorts-or-skirts/",
	"https://bettersquash.com/does-the-ball-have-to-bounce-in-squash/",
	"https://bettersquash.com/dont-become-too-ambitious-too-early/",
	"https://bettersquash.com/dont-play-with-shiny-squash-balls/",
	"https://bettersquash.com/dont-warm-up-before-you-play-squash-heat-up/",
	"https://bettersquash.com/each-squash-game-gets-progressively-more-important/",
	"https://bettersquash.com/figure-of-eight-solo-drill/",
	"https://bettersquash.com/find-a-training-partner-to-improve-your-squash/",
	"https://bettersquash.com/focus-on-improvement-during-practice-matches-not-winning/",
	"https://bettersquash.com/foot-faults-in-squash/",
	"https://bettersquash.com/getting-the-most-out-of-playing-against-weaker-opponents/",
	"https://bettersquash.com/here-are-3-crosscourt-shots-every-club-squash-player-should-know/",
	"https://bettersquash.com/hit-and-move-not-hit-watch-and-move/",
	"https://bettersquash.com/hit-every-squash-shot-with-intention/",
	"https://bettersquash.com/how-do-you-play-3-4-court-in-squash/",
	"https://bettersquash.com/how-hard-should-i-hit-the-squash-ball/",
	"https://bettersquash.com/how-high-should-you-hold-a-squash-racket/",
	"https://bettersquash.com/how-many-serves-are-you-allowed-in-squash/",
	"https://bettersquash.com/how-often-should-you-change-your-squash-racket/",
	"https://bettersquash.com/how-often-should-you-have-squash-coaching/",
	"https://bettersquash.com/how-often-should-you-replace-squash-strings/",
	"https://bettersquash.com/how-old-is-too-old-to-start-playing-squash/",
	"https://bettersquash.com/how-tightly-should-you-grip-the-squash-racket/",
	"https://bettersquash.com/how-to-break-free-of-your-squash-plateau/",
	"https://bettersquash.com/how-to-hit-the-ball-hard-in-squash-another-look/",
	"https://bettersquash.com/how-to-choose-the-right-squash-ball/",
	"https://bettersquash.com/how-to-hit-the-ball-hard-in-squash/",
	"https://bettersquash.com/how-to-hit-the-ball-hard-in-squash-another-look/",
	"https://bettersquash.com/how-to-hit-the-ball-softly-in-squash/",
	"https://bettersquash.com/how-to-use-the-knock-up-effectively-in-squash/",
	"https://bettersquash.com/how-to-watch-a-squash-match/",
	"https://bettersquash.com/how-were-wooden-squash-rackets-made/",
	"https://bettersquash.com/i-dont-care-if-squash-is-the-healthiest-sport/",
	"https://bettersquash.com/if-you-are-a-squash-player-think-like-a-football-team/",
	"https://bettersquash.com/if-you-lose-a-squash-match-can-you-blame-the-court/",
	"https://bettersquash.com/introduce-one-new-person-to-squash-this-year/",
	"https://bettersquash.com/is-buying-a-second-hand-squash-racket-a-good-idea/",
	"https://bettersquash.com/is-diving-allowed-in-squash/",
	"https://bettersquash.com/is-it-a-good-idea-to-try-to-copy-a-pro-squash-players-style/",
	"https://bettersquash.com/is-it-possible-to-play-squash-alone-as-a-beginner/",
	"https://bettersquash.com/is-it-time-to-switch-up-your-squash-rackets/",
	"https://bettersquash.com/is-it-time-to-train-for-some-squash-shot-combinations/",
	"https://bettersquash.com/is-squash-bad-for-your-body/",
	"https://bettersquash.com/is-swimming-good-for-squash-training/",
	"https://bettersquash.com/is-weight-training-good-for-squash/",
	"https://bettersquash.com/know-exactly-what-you-are-trying-to-do-in-each-squash-drill/",
	"https://bettersquash.com/lets-make-squash-courts-colourful/",
	"https://bettersquash.com/makins-crosscourt-oneshot/",
	"https://bettersquash.com/my-a-to-z-of-squash-2013-edition/",
	"https://bettersquash.com/other-racket-sports-are-not-squashs-enemy/",
	"https://bettersquash.com/over-running-shots-in-professional-squash/",
	"https://bettersquash.com/participation-coach-vs-elite-coach/",
	"https://bettersquash.com/perfect-gift-ideas-for-your-favourite-squash-players/",
	"https://bettersquash.com/photocoaching-back-corners-backhand/",
	"https://bettersquash.com/photocoaching-back-corners-forehand/",
	"https://bettersquash.com/play-a-squash-match-against-a-completely-new-opponent/",
	"https://bettersquash.com/play-different-players-not-just-better-players-part-1/",
	"https://bettersquash.com/play-weaker-players-not-just-better-players-part-2/",
	"https://bettersquash.com/play-with-a-vintage-racket-once-a-month/",
	"https://bettersquash.com/playing-against-physically-aggressive-squash-players/",
	"https://bettersquash.com/playing-squash-after-taking-a-long-break/",
	"https://bettersquash.com/please-play-the-lob-when-under-pressure/",
	"https://bettersquash.com/practice-your-serve-and-service-return/",
	"https://bettersquash.com/private-squash-court-in-manhattan/",
	"https://bettersquash.com/rackets-the-forefather-of-modern-squash/",
	"https://bettersquash.com/racketware-sensor/",
	"https://bettersquash.com/refereeing-course-from-players-perspectives/",
	"https://bettersquash.com/set-the-tone-against-new-squash-opponents/",
	"https://bettersquash.com/sharing-a-squash-court-for-solo-drilling/",
	"https://bettersquash.com/should-a-beginner-start-with-a-heavy-or-light-squash-racket/",
	"https://bettersquash.com/should-beginners-and-new-players-worry-about-squash-rackets/",
	"https://bettersquash.com/should-i-buy-expensive-squash-shoes/",
	"https://bettersquash.com/should-i-continue-playing-squash-when-i-am-injured/",
	"https://bettersquash.com/should-i-wear-squash-goggles/",
	"https://bettersquash.com/should-we-have-a-synchronised-team-squash-drill-championship/",
	"https://bettersquash.com/should-you-take-a-break-from-squash-in-the-summer/",
	"https://bettersquash.com/solo-squash-hitting-is-my-meditation/",
	"https://bettersquash.com/squash-and-body-shapes/",
	"https://bettersquash.com/squash-etiquette/",
	"https://bettersquash.com/squash-match-preparation-you-are-not-a-robot/",
	"https://bettersquash.com/squash-matches-can-turn-on-just-a-couple-of-points/",
	"https://bettersquash.com/squash-serving-tips-for-beginners/",
	"https://bettersquash.com/squash-plus-outdoor-court/",
	"https://bettersquash.com/squash-shoes-might-be-more-important-than-rackets/",
	"https://bettersquash.com/squash-tennis/",
	"https://bettersquash.com/squash-tips-for-solo-practice/",
	"https://bettersquash.com/squash-tips-turn-skill-acquisition-into-competitive-success/",
	"https://bettersquash.com/stop-playing-your-favourite-squash-shot/",
	"https://bettersquash.com/straight-only-any-length-condition-game-training/",
	"https://bettersquash.com/support-your-local-racket-specialist-shop/",
	"https://bettersquash.com/tell-me-your-job-and-ill-use-it-to-explain-squash-to-you/",
	"https://bettersquash.com/tennis-players-how-to-play-better-squash",
	"https://bettersquash.com/that-little-black-ball/",
	"https://bettersquash.com/there-is-only-now/",
	"https://bettersquash.com/the-alley-game/",
	"https://bettersquash.com/the-benefits-of-solo-practice-in-squash/",
	"https://bettersquash.com/the-global-rackets-stringing-rackets-sports-association/",
	"https://bettersquash.com/the-more-serious-you-are-the-less-creative-you-should-be/",
	"https://bettersquash.com/the-power-of-practice-in-squash/",
	"https://bettersquash.com/the-reverse-angle-aka-the-leisure-centre-boast/",
	"https://bettersquash.com/the-secret-to-great-squash/",
	"https://bettersquash.com/the-side-walls-can-be-your-friend-or-your-enemy/",
	"https://bettersquash.com/things-to-do-if-you-cant-have-on-court-coaching/",
	"https://bettersquash.com/things-to-do-to-get-the-most-from-coaching/",
	"https://bettersquash.com/things-to-know-before-you-have-coaching/",
	"https://bettersquash.com/time-for-a-squash-license/",
	"https://bettersquash.com/tips-to-maximise-your-squash-ghosting/",
	"https://bettersquash.com/turn-a-flicky-wrist-into-a-strong-forearm/",
	"https://bettersquash.com/two-fitness-concepts-to-improve-your-squash/",
	"https://bettersquash.com/use-visualisation-in-all-your-squash-training/",
	"https://bettersquash.com/using-the-full-height-of-the-squash-court/",
	"https://bettersquash.com/vintage-squash-racket-day/",
	"https://bettersquash.com/watch-great-squash-youll-learn-so-much/",
	"https://bettersquash.com/what-3-adjectives-describe-your-squash/",
	"https://bettersquash.com/what-are-conditioned-games-in-squash/",
	"https://bettersquash.com/what-are-graded-squash-tournaments/",
	"https://bettersquash.com/what-are-the-basic-shots-in-squash-called/",
	"https://bettersquash.com/what-are-the-lines-on-a-squash-court-for/",
	"https://bettersquash.com/what-are-your-squash-strengths-and-weaknesses-part-1/",
	"https://bettersquash.com/what-does-it-mean-to-carry-the-ball-in-squash/",
	"https://bettersquash.com/what-does-to-hit-the-ball-off-the-back-wall-mean-in-squash/",
	"https://bettersquash.com/what-happens-if-you-drop-your-squash-racket-in-the-middle-of-a-rally/",
	"https://bettersquash.com/what-is-a-foot-fault-in-squash/",
	"https://bettersquash.com/what-is-a-signature-shot-in-squash/",
	"https://bettersquash.com/what-is-a-squash-exhibition-match/",
	"https://bettersquash.com/what-is-a-tweener-in-squash/",
	"https://bettersquash.com/what-is-back-corner-circling-in-squash/",
	"https://bettersquash.com/what-is-fishing-in-squash/",
	"https://bettersquash.com/what-is-frontenis/",
	"https://bettersquash.com/what-is-it-like-to-play-on-a-glass-squash-court/",
	"https://bettersquash.com/what-is-rally-construction-in-squash/",
	"https://bettersquash.com/what-is-the-half-volley-in-squash/",
	"https://bettersquash.com/what-is-the-high-defensive-counter-drop-in-squash/",
	"https://bettersquash.com/what-is-the-perfect-practice-duration/",
	"https://bettersquash.com/what-is-the-split-step-in-squash/",
	"https://bettersquash.com/what-is-the-working-boast-in-squash/",
	"https://bettersquash.com/what-is-turning-in-squash/",
	"https://bettersquash.com/what-is-your-squash-mantra/",
	"https://bettersquash.com/what-level-of-squash-player-are-you/",
	"https://bettersquash.com/what-squash-players-can-learn-from-boxers-part-1/",
	"https://bettersquash.com/what-squash-players-can-learn-from-boxers-part-2/",
	"https://bettersquash.com/what-were-squash-racket-presses-used-for/",
	"https://bettersquash.com/whats-the-best-type-of-squash-racket-for-a-beginner-to-use/",
	"https://bettersquash.com/whats-the-best-way-to-improve-your-squash-footwork/",
	"https://bettersquash.com/whats-the-difference-between-a-stroke-and-a-let-in-squash/",
	"https://bettersquash.com/whats-the-difference-between-an-open-and-closed-squash-tournament/",
	"https://bettersquash.com/whats-the-difference-between-down-and-not-up-in-squash/",
	"https://bettersquash.com/whats-the-difference-between-hard-and-smart-training/",
	"https://bettersquash.com/whats-the-difference-between-reaction-time-and-anticipation/",
	"https://bettersquash.com/whats-the-difference-between-strategy-and-tactics-in-squash/",
	"https://bettersquash.com/whats-the-difference-between-the-warm-up-and-to-heat-up-in-squash/",
	"https://bettersquash.com/whats-the-point-of-the-commonwealth-squash-doubles/",
	"https://bettersquash.com/whats-the-secret-to-beating-tricky-squash-players/",
	"https://bettersquash.com/when-should-you-get-squash-coaching/",
	"https://bettersquash.com/when-should-you-progress-from-each-colour-dot-squash-ball/",
	"https://bettersquash.com/where-do-you-have-to-stand-to-receive-serve/",
	"https://bettersquash.com/where-exactly-is-the-t-in-squash/",
	"https://bettersquash.com/which-squash-ball-should-new-players-use/",
	"https://bettersquash.com/which-squash-racket-frame-shape-is-better/",
	"https://bettersquash.com/why-do-i-have-to-watch-the-ball-hit-my-strings/",
	"https://bettersquash.com/why-do-pro-squash-players-rally-to-the-back-so-much/",
	"https://bettersquash.com/why-do-pro-squash-players-sometimes/",
	"https://bettersquash.com/why-do-professional-squash-players-touch-the-side-wall-before-serving/",
	"https://bettersquash.com/why-i-think-most-drops-are-not-really-drops-at-all/",
	"https://bettersquash.com/why-increasing-the-difference-between-your-hardest-shot-and-your-softest-shot-can-be-the-key-to-your-squash-success/",
	"https://bettersquash.com/why-shadow-swinging-is-perfect-for-improving-your-strength-and-technique/",
	"https://bettersquash.com/why-the-average-shots-per-rally-is-a-great-indicator-of-your-squash-standard/",
	"https://bettersquash.com/why-you-should-watch-a-coaching-video-more-than-once/",
	"https://bettersquash.com/world-squash-day/",
	"https://bettersquash.com/your-drop-shot-is-only-as-good-as-your-deep-drive/",
	"https://bettersquash.com/your-moving-speed-versus-your-hitting-speed/"
    
]

def check_url(url):
    try:
        response = requests.head(url, allow_redirects=True)
        return response.url, response.status_code
    except requests.RequestException as e:
        return None, str(e)

def main():
    results = []
    for url in urls:
        final_url, status_code = check_url(url)
        results.append((url, final_url, status_code))

    for original_url, final_url, status_code in results:
        print(f"Original URL: {original_url}")
        print(f"Final URL: {final_url}")
        print(f"Status Code: {status_code}")
        print("-" * 40)

if __name__ == "__main__":
    main()